### PR TITLE
Travis CI → GitHub Actions

### PR DESCRIPTION
**Pull request by Gallaecio**
[Test results](https://github.com/Gallaecio/queuelib/runs/2094934469).

### CODE REVIEW

**Comment by elacuesta** [comment]
Updated after #37, new test run [here](https://github.com/Gallaecio/queuelib/actions/runs/713498418)

**Review by elacuesta — APPROVED** [review]
Looks great to me 🚀 

Is the `PYPI_TOKEN` secret already configured in the repo? I didn't want to merge without making sure of that.

**Comment by Gallaecio** [comment]
> Is the `PYPI_TOKEN` secret already configured in the repo?

It’s not, and I cannot add it myself yet.

**Comment by Gallaecio** [comment]
Secret set.

**Pull request merged**
